version: 2.1
orbs:
    browser-tools: circleci/browser-tools@1.4.3
jobs:
    build:
        working_directory: ~/ngx-gantt
        docker:
            - image: cimg/node:20.16.0-browsers
        steps:
            - browser-tools/install-chrome
            - checkout
            - run: |
                  node --version
                  google-chrome --version
                  which google-chrome
            - restore_cache:
                  key: ngx-gantt-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - run: npm install --force
            - save_cache:
                  key: ngx-gantt-{{ .Branch }}-{{ checksum "package-lock.json" }}
                  paths:
                      - 'node_modules'
            - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
            - run: npm run lint -- --quiet
            - run: npm run report-coverage
            - run: npm run build
